sudo: required

language: node_js

node_js:
  - "8"

install:
  - npm install


script:
  - echo 'Nothing to build'
  # - npm test
  # - npm run build-prod

install:
  - npm install
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: testnet.tomoswap.com
    region: ap-southeast-1
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: develop
