sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

services:
  - docker

install:
  - NODE_ENV=production npm ci


script:
  - echo 'Nothing to build'
  # - npm test
  # - npm run build-prod

after_success:
  - docker --version
  - docker build -f Dockerfile -t chaintex/tomoswap:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
